<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiciosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('servicios')->delete();
        
        \DB::table('servicios')->insert(array (
            0 => 
            array (
                'id' => 3,
                'nombre' => 'Certificado de registro',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '4.00',
                'porcentaje' => '0.00',
                'ordinario' => '415.00',
                'urgente' => '830.00',
                'extra_urgente' => '1245.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:27:55',
                'updated_at' => '2023-03-23 15:27:55',
            ),
            1 => 
            array (
                'id' => 4,
                'nombre' => 'Certificado de registro electrónico',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '4.50',
                'porcentaje' => '0.00',
                'ordinario' => '467.00',
                'urgente' => '882.00',
                'extra_urgente' => '1297.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:29:46',
                'updated_at' => '2023-03-23 15:29:46',
            ),
            2 => 
            array (
                'id' => 5,
                'nombre' => 'Certificado negativo catastral',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '4.00',
                'porcentaje' => '0.00',
                'ordinario' => '415.00',
                'urgente' => '830.00',
                'extra_urgente' => '1245.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:30:30',
                'updated_at' => '2023-03-23 15:30:30',
            ),
            3 => 
            array (
                'id' => 6,
                'nombre' => 'Certificado de registro con colindancias',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '4.00',
                'porcentaje' => '0.00',
                'ordinario' => '415.00',
                'urgente' => '1038.00',
                'extra_urgente' => '1556.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:33:35',
                'updated_at' => '2023-03-23 15:33:35',
            ),
            4 => 
            array (
                'id' => 7,
                'nombre' => 'Certificado de historia catastral',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '1.00',
                'porcentaje' => '0.00',
                'ordinario' => '104.00',
                'urgente' => '208.00',
                'extra_urgente' => '312.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:37:51',
                'updated_at' => '2023-03-23 15:37:51',
            ),
            5 => 
            array (
                'id' => 8,
                'nombre' => 'Certificado de historia catastral hasta 5 movimientos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '207.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 15:39:09',
                'updated_at' => '2023-03-23 15:41:44',
            ),
            6 => 
            array (
                'id' => 9,
                'nombre' => 'Certificado de historia catastral de 6 a 10 movimientos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '307.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 15:41:16',
                'updated_at' => '2023-03-23 15:42:06',
            ),
            7 => 
            array (
                'id' => 10,
                'nombre' => 'Certificado de historia catastral de 11 a 15 movimientos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '359.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:42:40',
                'updated_at' => '2023-03-23 15:42:40',
            ),
            8 => 
            array (
                'id' => 11,
                'nombre' => 'Certificado de historia catastral de mas de 15 movimientos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '521.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:43:12',
                'updated_at' => '2023-03-23 15:43:12',
            ),
            9 => 
            array (
                'id' => 12,
                'nombre' => ' Copias impresas de planos catastrales digitalizados: Manzaneros',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '507.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 15:50:44',
                'updated_at' => '2023-03-23 15:52:51',
            ),
            10 => 
            array (
                'id' => 13,
                'nombre' => ' Copias impresas de planos catastrales digitalizados: De los Municipios de Morelia, Uruapan y Zamora, escala 1:10,000.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '3140.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:52:42',
                'updated_at' => '2023-03-23 15:52:42',
            ),
            11 => 
            array (
                'id' => 14,
                'nombre' => ' Copias impresas de planos catastrales digitalizados: De los Municipios de Apatzingán, Cd. Hidalgo, Jacona, La Piedad, Lázaro Cárdenas, Los Reyes, Pátzcuaro, Puruándiro, Tacámbaro, Sahuayo y Zitácuaro, escala 1:7,500.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2391.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:53:29',
                'updated_at' => '2023-03-23 15:53:29',
            ),
            12 => 
            array (
                'id' => 15,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: De los Municipios de Coeneo, Cotija, Cuitzeo, Huandacareo, Jiquilpan, Maravatío, Paracho, Purépero, Quiroga, Salvador Escalante, Tangancícuaro, Tarímbaro, Venustiano Carranza, Yurécuaro, Zacapu y Zinapécuaro, escala 1:7,500.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1658.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:54:08',
                'updated_at' => '2023-03-23 15:54:08',
            ),
            13 => 
            array (
                'id' => 16,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: Manzaneros. Concurvas de nivel',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1014.00',
                'urgente' => '2028.00',
                'extra_urgente' => '3042.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 15:59:50',
                'updated_at' => '2023-03-23 15:59:50',
            ),
            14 => 
            array (
                'id' => 17,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: Con curvas de nivel. De los Municipios de Morelia, Uruapan y Zamora, escala 1:10,000',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '6280.00',
                'urgente' => '12560.00',
                'extra_urgente' => '18840.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:02:24',
                'updated_at' => '2023-05-11 17:05:51',
            ),
            15 => 
            array (
                'id' => 18,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: Con curvas de nivel. De los Municipios de Apatzingán, Cd. Hidalgo, Jacona, La Piedad, Lázaro Cárdenas, Los Reyes, Pátzcuaro, Puruándiro, Tacámbaro, Sahuayo y Zitácuaro, escala 1:7,500.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '4782.00',
                'urgente' => '9564.00',
                'extra_urgente' => '14346.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:03:26',
                'updated_at' => '2023-05-11 17:05:43',
            ),
            16 => 
            array (
                'id' => 19,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: Con curvas de nivel. De los Municipios de Coeneo, Cotija, Cuitzeo, Huandacareo, Jiquilpan, Maravatío, Paracho, Purépero, Quiroga, Salvador Escalante, Tangancícuaro, Tarímbaro, Venustiano Carranza, Yurécuaro, Zacapu y Zinapécuaro, escala 1:7,500.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '3316.00',
                'urgente' => '6632.00',
                'extra_urgente' => '9948.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:04:21',
                'updated_at' => '2023-05-11 17:05:34',
            ),
            17 => 
            array (
                'id' => 20,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: Manzanero, en formato dwf.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '586.00',
                'urgente' => '1172.00',
                'extra_urgente' => '1758.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:06:12',
                'updated_at' => '2023-05-11 17:04:54',
            ),
            18 => 
            array (
                'id' => 21,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: De sector, en formato dwf, por cada manzana existente en el mismo.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '104.00',
                'urgente' => '208.00',
                'extra_urgente' => '312.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:06:47',
                'updated_at' => '2023-05-11 17:04:43',
            ),
            19 => 
            array (
                'id' => 22,
                'nombre' => 'Copias impresas de planos catastrales digitalizados: Por fotografía aérea escaneada en archivo digital en formato dwf.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '800.00',
                'urgente' => '1600.00',
                'extra_urgente' => '2400.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:07:22',
                'updated_at' => '2023-03-23 16:07:22',
            ),
            20 => 
            array (
                'id' => 23,
                'nombre' => 'Copias en archivo digital en formato dwf: De los municipios de La Piedad, Morelia, Uruapan y Zamora.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '12485.00',
                'urgente' => '24970.00',
                'extra_urgente' => '37455.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:08:59',
                'updated_at' => '2023-03-23 16:08:59',
            ),
            21 => 
            array (
                'id' => 24,
                'nombre' => 'Copias en archivo digital en formato dwf: De los municipios de Apatzingán, Jacona, Jiquilpan, Los Reyes, Lázaro Cárdenas, Maravatío, Pátzcuaro, Puruándiro, Sahuayo y Zitácuaro.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '9175.00',
                'urgente' => '18350.00',
                'extra_urgente' => '27525.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:09:24',
                'updated_at' => '2023-03-23 16:09:24',
            ),
            22 => 
            array (
                'id' => 25,
                'nombre' => 'Copias en archivo digital en formato dwf: De los municipios de Ciudad Hidalgo, Coeneo, Cotija, Cuitzeo, Huandacareo, Paracho, Purépero, Quiroga, Salvador Escalante, Tacámbaro, Tangancícuaro, Venustiano Carranza, Yurécuaro, Zacapu y Zinapécuaro.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '6111.00',
                'urgente' => '12222.00',
                'extra_urgente' => '18333.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:09:52',
                'updated_at' => '2023-03-23 16:09:52',
            ),
            23 => 
            array (
                'id' => 26,
                'nombre' => 'Copias en archivo digital en formato dwf: De los planos de valores unitarios de terreno urbano por sector de los municipios de Apatzingán, La Piedad, Lázaro Cárdenas, Morelia, Uruapan y Zamora.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '7710.00',
                'urgente' => '15420.00',
                'extra_urgente' => '23130.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:11:01',
                'updated_at' => '2023-03-23 16:11:01',
            ),
            24 => 
            array (
                'id' => 27,
                'nombre' => 'Copias en archivo digital en formato dwf: De los planos de valores unitarios de terreno urbano de los demás municipios con los que se cuenta planos de valores autorizados por el Congreso.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '7644.00',
                'urgente' => '15288.00',
                'extra_urgente' => '22932.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:11:38',
                'updated_at' => '2023-03-23 16:11:38',
            ),
            25 => 
            array (
                'id' => 28,
                'nombre' => 'Copias en archivo digital en formato dwf: Planos catastrales no digitalizados.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '806.00',
                'urgente' => '1612.00',
                'extra_urgente' => '2418.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:12:29',
                'updated_at' => '2023-03-23 16:12:52',
            ),
            26 => 
            array (
                'id' => 29,
                'nombre' => 'Para predios urbanos, de 1 a 1,000 m²',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '4312.00',
                'urgente' => '8624.00',
                'extra_urgente' => '12936.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 6,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:16:07',
                'updated_at' => '2023-03-23 16:16:07',
            ),
            27 => 
            array (
                'id' => 30,
                'nombre' => 'Para predios urbanos, de 1,001 m²  a  5,000 m²	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '5468.00',
                'urgente' => '10936.00',
                'extra_urgente' => '16404.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 6,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:16:28',
                'updated_at' => '2023-03-23 16:16:28',
            ),
            28 => 
            array (
                'id' => 31,
                'nombre' => 'Para predios urbanos, de 5,001 m²  a 10,000 m²	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '7290.00',
                'urgente' => '14580.00',
                'extra_urgente' => '21870.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 6,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:16:48',
                'updated_at' => '2023-03-23 16:16:48',
            ),
            29 => 
            array (
                'id' => 32,
                'nombre' => 'Para predios urbanos, de 10,001 m² en adelante.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '10328.00',
                'urgente' => '20656.00',
                'extra_urgente' => '30984.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 6,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:17:15',
                'updated_at' => '2023-03-23 16:17:15',
            ),
            30 => 
            array (
                'id' => 33,
                'nombre' => 'Urbanos, ubicados en cualquier población del Estado.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2337.00',
                'urgente' => '4674.00',
                'extra_urgente' => '7011.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 7,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:22:22',
                'updated_at' => '2023-03-23 16:22:22',
            ),
            31 => 
            array (
                'id' => 34,
                'nombre' => 'Rústicos en cualquier lugar del Estado:	Ubicados dentro de un radio hasta de 20 kilómetros, teniendo como centro la oficina recaudadora donde se registra.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2085.00',
                'urgente' => '4170.00',
                'extra_urgente' => '6255.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 7,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:23:24',
                'updated_at' => '2023-03-23 16:23:24',
            ),
            32 => 
            array (
                'id' => 35,
                'nombre' => 'Rústicos en cualquier lugar del Estado:	Ubicados dentro de un radio hasta de 50 kilómetros, teniendo como centro la oficina recaudadora donde se registra.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2163.00',
                'urgente' => '4326.00',
                'extra_urgente' => '6489.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 7,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:24:02',
                'updated_at' => '2023-03-23 16:24:02',
            ),
            33 => 
            array (
                'id' => 36,
                'nombre' => 'Rústicos en cualquier lugar del Estado:	Ubicados dentro de un radio superior a los 50 kilómetros, teniendo como centro la oficina recaudadora donde se registra.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2949.00',
                'urgente' => '5898.00',
                'extra_urgente' => '8847.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 7,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:24:31',
                'updated_at' => '2023-03-23 16:24:31',
            ),
            34 => 
            array (
                'id' => 37,
                'nombre' => 'Sobre predios ubicados dentro del área de la población donde se encuentra la oficina recaudadora.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '670.00',
                'urgente' => '1340.00',
                'extra_urgente' => '2010.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 8,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:32:51',
                'updated_at' => '2023-03-23 16:32:51',
            ),
            35 => 
            array (
                'id' => 38,
                'nombre' => 'Sobre predios ubicados fuera de la localidad donde se encuentre la oficina recaudadora dentro de un radio hasta de 20 kilómetros.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1068.00',
                'urgente' => '2136.00',
                'extra_urgente' => '3204.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 8,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:33:14',
                'updated_at' => '2023-03-23 16:33:14',
            ),
            36 => 
            array (
                'id' => 39,
                'nombre' => 'Sobre predios ubicados fuera de la localidad donde se encuentre la oficina recaudadora dentro de un radio hasta de 50 kilómetros.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1715.00',
                'urgente' => '3430.00',
                'extra_urgente' => '5145.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 8,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:33:35',
                'updated_at' => '2023-03-23 16:33:35',
            ),
            37 => 
            array (
                'id' => 40,
                'nombre' => 'Sobre predios ubicados fuera de la localidad donde se encuentre la oficina recaudadora dentro de un radio superior a 50 kilómetros.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1931.00',
                'urgente' => '3862.00',
                'extra_urgente' => '5793.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 8,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:33:58',
                'updated_at' => '2023-03-23 16:33:58',
            ),
            38 => 
            array (
                'id' => 41,
                'nombre' => 'Por cuenta catastral analizada y reestructurada, tratándose de fraccionamientos y condominios.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2885.00',
                'urgente' => '5770.00',
                'extra_urgente' => '8655.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 9,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:37:52',
                'updated_at' => '2023-03-23 16:37:52',
            ),
            39 => 
            array (
                'id' => 42,
                'nombre' => 'Otras cuentas catastrales analizadas y reestructuradas distintas de fraccionamientos y condominios.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1899.00',
                'urgente' => '3798.00',
                'extra_urgente' => '5697.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 9,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:38:17',
                'updated_at' => '2023-03-23 16:38:17',
            ),
            40 => 
            array (
                'id' => 43,
                'nombre' => 'De fraccionamientos, condominios y conjuntos habitacionales, por cada predio que surja.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '149.00',
                'urgente' => '298.00',
                'extra_urgente' => '447.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 10,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:40:40',
                'updated_at' => '2023-03-23 16:40:40',
            ),
            41 => 
            array (
                'id' => 44,
                'nombre' => 'De cualquier otro tipo de inmueble.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '207.00',
                'urgente' => '414.00',
                'extra_urgente' => '621.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 10,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:41:08',
                'updated_at' => '2023-03-23 16:41:08',
            ),
            42 => 
            array (
                'id' => 45,
                'nombre' => 'Variación Catastral Vivienda',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1763.00',
                'urgente' => '3526.00',
                'extra_urgente' => '5289.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 11,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:45:09',
                'updated_at' => '2023-03-23 16:46:11',
            ),
            43 => 
            array (
                'id' => 46,
                'nombre' => 'Variación Catastral Otro tipo de inmueble',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1763.00',
                'urgente' => '3526.00',
                'extra_urgente' => '5289.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 11,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-23 16:45:48',
                'updated_at' => '2023-03-23 16:46:05',
            ),
            44 => 
            array (
                'id' => 47,
                'nombre' => 'Solicitud de Predio Ignorado',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1763.00',
                'urgente' => '3526.00',
                'extra_urgente' => '5289.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 12,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:48:21',
                'updated_at' => '2023-03-23 16:48:21',
            ),
            45 => 
            array (
                'id' => 48,
                'nombre' => 'Por autorización e inscripción de peritos valuadores de bienes inmuebles.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '4075.00',
                'urgente' => '8150.00',
                'extra_urgente' => '12225.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 13,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:49:49',
                'updated_at' => '2023-03-23 16:49:49',
            ),
            46 => 
            array (
                'id' => 49,
                'nombre' => 'Por refrendo anual de la autorización de perito valuador.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2422.00',
                'urgente' => '4844.00',
                'extra_urgente' => '7266.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 13,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:50:10',
                'updated_at' => '2023-03-23 16:50:10',
            ),
            47 => 
            array (
                'id' => 50,
                'nombre' => '	Derecho a examen de conocimientos que al efecto practique el Instituto a través de la Dirección de Catastro',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '916.00',
                'urgente' => '1832.00',
                'extra_urgente' => '2748.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 13,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:50:42',
                'updated_at' => '2023-03-23 16:50:42',
            ),
            48 => 
            array (
                'id' => 51,
                'nombre' => 'Por revisión de examen que solicite el sustentante	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '916.00',
                'urgente' => '1832.00',
                'extra_urgente' => '2748.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 13,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:51:04',
                'updated_at' => '2023-03-23 16:51:04',
            ),
            49 => 
            array (
                'id' => 52,
                'nombre' => 'Por información respecto de los nombres de colindantes, a propietarios o poseedores de predios registrados.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '436.00',
                'urgente' => '872.00',
                'extra_urgente' => '1308.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 14,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-23 16:55:49',
                'updated_at' => '2023-03-23 16:55:49',
            ),
            50 => 
            array (
                'id' => 53,
                'nombre' => 'Si la información que proporcionen los interesados es suficiente.	',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '100.00',
                'urgente' => '200.00',
                'extra_urgente' => '300.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 15,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 14:56:43',
                'updated_at' => '2023-03-27 14:56:43',
            ),
            51 => 
            array (
                'id' => 54,
                'nombre' => 'Si se requieren investigaciones adicionales a la información proporcionada por los interesados.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '116.00',
                'urgente' => '232.00',
                'extra_urgente' => '348.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 15,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 14:57:02',
                'updated_at' => '2023-03-27 14:57:02',
            ),
            52 => 
            array (
                'id' => 55,
                'nombre' => 'Copias simples, por página',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '23.00',
                'urgente' => '46.00',
                'extra_urgente' => '69.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 16,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 14:59:02',
                'updated_at' => '2023-03-27 14:59:02',
            ),
            53 => 
            array (
                'id' => 56,
                'nombre' => 'Copias certificadas, por página',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '44.00',
                'urgente' => '88.00',
                'extra_urgente' => '132.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 16,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 14:59:29',
                'updated_at' => '2023-03-27 14:59:29',
            ),
            54 => 
            array (
                'id' => 57,
                'nombre' => 'Consulta del acervo catastral',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '1.00',
                'porcentaje' => '0.00',
                'ordinario' => '104.00',
                'urgente' => '208.00',
                'extra_urgente' => '312.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 16,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:05:11',
                'updated_at' => '2023-03-27 15:05:11',
            ),
            55 => 
            array (
                'id' => 58,
                'nombre' => 'Consulta del acervo catastral cuando se trate de oficinas foráneas	',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '2.00',
                'porcentaje' => '0.00',
                'ordinario' => '208.00',
                'urgente' => '416.00',
                'extra_urgente' => '624.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 16,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:05:35',
                'updated_at' => '2023-03-27 15:05:35',
            ),
            56 => 
            array (
                'id' => 59,
                'nombre' => 'Para predios urbanos, de 1 a 1,000 m²',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '4312.00',
                'urgente' => '8624.00',
                'extra_urgente' => '12936.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 17,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:10:22',
                'updated_at' => '2023-03-27 15:10:22',
            ),
            57 => 
            array (
                'id' => 60,
                'nombre' => 'Para predios urbanos, de 1,001 m² a 5,000 m²',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '5468.00',
                'urgente' => '10936.00',
                'extra_urgente' => '16404.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 17,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:10:43',
                'updated_at' => '2023-03-27 15:10:43',
            ),
            58 => 
            array (
                'id' => 61,
                'nombre' => 'Para predios urbanos, de 5,001 m² a 10,000 m²',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '7290.00',
                'urgente' => '14580.00',
                'extra_urgente' => '21870.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 17,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:11:00',
                'updated_at' => '2023-03-27 15:11:00',
            ),
            59 => 
            array (
                'id' => 62,
                'nombre' => 'Para predios urbanos, de 10,001 m² en adelante',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '10328.00',
                'urgente' => '20656.00',
                'extra_urgente' => '30984.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 17,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:11:17',
                'updated_at' => '2023-03-27 15:11:17',
            ),
            60 => 
            array (
                'id' => 63,
                'nombre' => 'Modificación de datos administrativos catastrales',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '267.00',
                'urgente' => '534.00',
                'extra_urgente' => '801.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 18,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:13:10',
                'updated_at' => '2023-03-27 15:13:10',
            ),
            61 => 
            array (
                'id' => 64,
                'nombre' => 'Cédula de actualización de predios rústicos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '267.00',
                'urgente' => '534.00',
                'extra_urgente' => '801.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 19,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:14:30',
                'updated_at' => '2023-03-27 15:14:30',
            ),
            62 => 
            array (
                'id' => 65,
                'nombre' => 'Cédula de actualización de predios urbanos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '267.00',
                'urgente' => '534.00',
                'extra_urgente' => '801.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 19,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:14:58',
                'updated_at' => '2023-03-27 15:14:58',
            ),
            63 => 
            array (
                'id' => 66,
            'nombre' => 'Revisión de Aviso y/o cancelación (predio rústico)',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '288.00',
                'urgente' => '576.00',
                'extra_urgente' => '864.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 20,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:17:07',
                'updated_at' => '2023-03-27 15:17:07',
            ),
            64 => 
            array (
                'id' => 67,
            'nombre' => 'Revisión de Aviso y/o cancelación (predio urbano)',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '288.00',
                'urgente' => '576.00',
                'extra_urgente' => '864.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 20,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:17:26',
                'updated_at' => '2023-03-27 15:17:26',
            ),
            65 => 
            array (
                'id' => 68,
                'nombre' => 'Aviso Aclaratorio de predio rústico o urbano.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '267.00',
                'urgente' => '534.00',
                'extra_urgente' => '801.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 21,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:18:22',
                'updated_at' => '2023-03-27 15:18:22',
            ),
            66 => 
            array (
                'id' => 69,
                'nombre' => 'Por resolución administrativa emitida por el Registro Agrario Nacional o Instituto Nacional del Suelo Sustentable.',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '961.00',
                'urgente' => '1922.00',
                'extra_urgente' => '2883.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 22,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:20:02',
                'updated_at' => '2023-03-27 15:20:02',
            ),
            67 => 
            array (
                'id' => 70,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 1 a 4. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1001.00',
                'urgente' => '2002.00',
                'extra_urgente' => '3003.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:28:16',
                'updated_at' => '2023-03-27 15:28:16',
            ),
            68 => 
            array (
                'id' => 71,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 1 a 4. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1534.00',
                'urgente' => '3068.00',
                'extra_urgente' => '4602.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:28:35',
                'updated_at' => '2023-03-27 15:28:35',
            ),
            69 => 
            array (
                'id' => 72,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 5 a 20. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '959.00',
                'urgente' => '1918.00',
                'extra_urgente' => '2877.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:29:20',
                'updated_at' => '2023-03-27 15:29:20',
            ),
            70 => 
            array (
                'id' => 73,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 5 a 20. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1278.00',
                'urgente' => '2556.00',
                'extra_urgente' => '3834.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:29:49',
                'updated_at' => '2023-03-27 15:29:49',
            ),
            71 => 
            array (
                'id' => 74,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 21 a 50. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '852.00',
                'urgente' => '1704.00',
                'extra_urgente' => '2556.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:30:28',
                'updated_at' => '2023-03-27 15:30:28',
            ),
            72 => 
            array (
                'id' => 75,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 21 a 50. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1022.00',
                'urgente' => '2044.00',
                'extra_urgente' => '3066.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:30:51',
                'updated_at' => '2023-03-27 15:30:51',
            ),
            73 => 
            array (
                'id' => 76,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 51 a 100. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '639.00',
                'urgente' => '1278.00',
                'extra_urgente' => '1917.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:31:19',
                'updated_at' => '2023-03-27 15:31:19',
            ),
            74 => 
            array (
                'id' => 77,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 51 a 100. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '767.00',
                'urgente' => '1534.00',
                'extra_urgente' => '2301.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:31:36',
                'updated_at' => '2023-03-27 15:31:36',
            ),
            75 => 
            array (
                'id' => 78,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 101 a 500	. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '266.00',
                'urgente' => '532.00',
                'extra_urgente' => '798.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:32:16',
                'updated_at' => '2023-03-27 15:32:16',
            ),
            76 => 
            array (
                'id' => 79,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 101 a 500	. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '320.00',
                'urgente' => '640.00',
                'extra_urgente' => '960.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:32:36',
                'updated_at' => '2023-03-27 15:32:36',
            ),
            77 => 
            array (
                'id' => 80,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 501 a 1000. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '224.00',
                'urgente' => '448.00',
                'extra_urgente' => '672.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:33:17',
                'updated_at' => '2023-03-27 15:33:17',
            ),
            78 => 
            array (
                'id' => 81,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 1 a 4. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '13313.00',
                'urgente' => '26626.00',
                'extra_urgente' => '39939.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-27 15:34:02',
                'updated_at' => '2023-05-15 12:48:14',
            ),
            79 => 
            array (
                'id' => 82,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 1 a 4. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '19728.00',
                'urgente' => '39456.00',
                'extra_urgente' => '59184.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:34:28',
                'updated_at' => '2023-03-27 15:34:28',
            ),
            80 => 
            array (
                'id' => 83,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 5 a 10. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '12248.00',
                'urgente' => '24496.00',
                'extra_urgente' => '36744.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:35:00',
                'updated_at' => '2023-03-27 15:35:00',
            ),
            81 => 
            array (
                'id' => 84,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 5 a 10. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '15717.00',
                'urgente' => '31434.00',
                'extra_urgente' => '47151.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:35:19',
                'updated_at' => '2023-03-27 15:35:19',
            ),
            82 => 
            array (
                'id' => 85,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 11 a 20. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '10118.00',
                'urgente' => '20236.00',
                'extra_urgente' => '30354.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:35:50',
                'updated_at' => '2023-03-27 15:35:50',
            ),
            83 => 
            array (
                'id' => 86,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 11 a 20. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '11635.00',
                'urgente' => '23270.00',
                'extra_urgente' => '34905.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:36:07',
                'updated_at' => '2023-03-27 15:36:07',
            ),
            84 => 
            array (
                'id' => 87,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 21 a 50. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '8520.00',
                'urgente' => '17040.00',
                'extra_urgente' => '25560.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:36:35',
                'updated_at' => '2023-03-27 15:36:35',
            ),
            85 => 
            array (
                'id' => 88,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 21 a 50. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '9798.00',
                'urgente' => '19596.00',
                'extra_urgente' => '29394.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-27 15:36:53',
                'updated_at' => '2023-05-15 12:48:08',
            ),
            86 => 
            array (
                'id' => 89,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 	51 a 100. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '7455.00',
                'urgente' => '14910.00',
                'extra_urgente' => '22365.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:37:19',
                'updated_at' => '2023-03-27 15:37:19',
            ),
            87 => 
            array (
                'id' => 90,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de 51 a 100. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '8573.00',
                'urgente' => '17146.00',
                'extra_urgente' => '25719.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:37:39',
                'updated_at' => '2023-03-27 15:37:39',
            ),
            88 => 
            array (
                'id' => 91,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de más de 100. Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '6923.00',
                'urgente' => '13846.00',
                'extra_urgente' => '20769.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:38:13',
                'updated_at' => '2023-03-27 15:38:13',
            ),
            89 => 
            array (
                'id' => 92,
                'nombre' => 'Hectareas o kilometro lineal de cobertura de más de 100. Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '7961.00',
                'urgente' => '15922.00',
                'extra_urgente' => '23883.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-27 15:38:32',
                'updated_at' => '2023-05-15 12:48:04',
            ),
            90 => 
            array (
                'id' => 93,
                'nombre' => 'Puntos decontrol de 1 a 5 Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2130.00',
                'urgente' => '4260.00',
                'extra_urgente' => '6390.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:39:29',
                'updated_at' => '2023-03-27 15:39:29',
            ),
            91 => 
            array (
                'id' => 94,
                'nombre' => 'Puntos decontrol de 1 a 5 Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2343.00',
                'urgente' => '4686.00',
                'extra_urgente' => '7029.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:39:49',
                'updated_at' => '2023-03-27 15:39:49',
            ),
            92 => 
            array (
                'id' => 95,
                'nombre' => 'Puntos decontrol de 6 a 20 Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1917.00',
                'urgente' => '3834.00',
                'extra_urgente' => '5751.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:40:10',
                'updated_at' => '2023-03-27 15:40:10',
            ),
            93 => 
            array (
                'id' => 96,
                'nombre' => 'Puntos decontrol de 6 a 20 Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2109.00',
                'urgente' => '4218.00',
                'extra_urgente' => '6327.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-27 15:40:24',
                'updated_at' => '2023-05-15 12:47:55',
            ),
            94 => 
            array (
                'id' => 97,
                'nombre' => 'Puntos de control de 21 a 50 Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1598.00',
                'urgente' => '3196.00',
                'extra_urgente' => '4794.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:41:01',
                'updated_at' => '2023-03-27 15:41:01',
            ),
            95 => 
            array (
                'id' => 98,
                'nombre' => 'Puntos de control de 21 a 50 Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1757.00',
                'urgente' => '3514.00',
                'extra_urgente' => '5271.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:41:19',
                'updated_at' => '2023-03-27 15:41:19',
            ),
            96 => 
            array (
                'id' => 99,
                'nombre' => 'Puntos de control de 51 a 100 Vegetación no densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1385.00',
                'urgente' => '2770.00',
                'extra_urgente' => '4155.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:41:42',
                'updated_at' => '2023-03-27 15:41:42',
            ),
            97 => 
            array (
                'id' => 100,
                'nombre' => 'Puntos de control de 51 a 100 Vegetación densa',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '1523.00',
                'urgente' => '3046.00',
                'extra_urgente' => '4569.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:41:57',
                'updated_at' => '2023-03-27 15:41:57',
            ),
            98 => 
            array (
                'id' => 101,
            'nombre' => 'Apoyo terrestre con Sistema de Posicionamiento Global (GPS) por kilómetro cuadrado de cobertura',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '5102.00',
                'urgente' => '10204.00',
                'extra_urgente' => '15306.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:42:43',
                'updated_at' => '2023-03-27 15:42:43',
            ),
            99 => 
            array (
                'id' => 102,
            'nombre' => '	Fotografía aérea georeferenciada (Ortofoto) digital, por mosaico de un kilómetro cuadrado de cobertura',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '2430.00',
                'urgente' => '4860.00',
                'extra_urgente' => '7290.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:43:01',
                'updated_at' => '2023-03-27 15:43:01',
            ),
            100 => 
            array (
                'id' => 103,
            'nombre' => 'Restitución de manzana (sujeta a disposición de software, equipo y personal capacitado)',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '851.00',
                'urgente' => '1702.00',
                'extra_urgente' => '2553.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:43:34',
                'updated_at' => '2023-03-27 15:43:34',
            ),
            101 => 
            array (
                'id' => 104,
                'nombre' => 'Frente Lineal de Manzanas, por predio',
                'tipo' => 'fija',
                'estado' => 'inactivo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '12.00',
                'urgente' => '24.00',
                'extra_urgente' => '36.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 23,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:44:10',
                'updated_at' => '2023-03-27 15:44:10',
            ),
            102 => 
            array (
                'id' => 105,
                'nombre' => 'Ubicación cartográfica para la asignación correcta de clave catastral',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '180.00',
                'urgente' => '360.00',
                'extra_urgente' => '540.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 24,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:46:01',
                'updated_at' => '2023-03-27 15:46:01',
            ),
            103 => 
            array (
                'id' => 106,
                'nombre' => 'Ubicación cartográfica por cambio de localidad',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '180.00',
                'urgente' => '360.00',
                'extra_urgente' => '540.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 25,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:47:06',
                'updated_at' => '2023-03-27 15:47:06',
            ),
            104 => 
            array (
                'id' => 107,
                'nombre' => 'Georreferenciación de croquis administrativos del catastro',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => '0.00',
                'ordinario' => '587.00',
                'urgente' => '1174.00',
                'extra_urgente' => '1761.00',
                'clave_ingreso' => NULL,
                'categoria_servicio_id' => 26,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-27 15:47:58',
                'updated_at' => '2023-03-27 15:47:58',
            ),
            105 => 
            array (
                'id' => 108,
                'nombre' => 'Para predios rústicos Hasta de 00-00-01 A  01-00-00 HAS GRUPO 1',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => NULL,
                'ordinario' => '5362.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => '3213',
                'categoria_servicio_id' => 6,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-05-19 15:09:41',
                'updated_at' => '2023-05-19 15:09:41',
            ),
            106 => 
            array (
                'id' => 109,
                'nombre' => 'Para predios rústicos Hasta de 00-00-01 A  01-00-00 HAS GRUPO 2',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => NULL,
                'ordinario' => '6713.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => '324',
                'categoria_servicio_id' => 6,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-05-19 15:10:06',
                'updated_at' => '2023-05-19 15:10:06',
            ),
            107 => 
            array (
                'id' => 110,
                'nombre' => 'Para predios rústicos Hasta de 00-00-01 A  01-00-00 HAS GRUPO 3',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => NULL,
                'ordinario' => '8034.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => '3525',
                'categoria_servicio_id' => 6,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-05-19 15:10:46',
                'updated_at' => '2023-05-19 15:10:46',
            ),
            108 => 
            array (
                'id' => 111,
                'nombre' => 'Para predios rústicos Hasta de 00-00-01 A 01-00-00 HAS GRUPO 4',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'porcentaje' => NULL,
                'ordinario' => '10802.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'clave_ingreso' => '43534534',
                'categoria_servicio_id' => 6,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-05-19 15:11:26',
                'updated_at' => '2023-05-19 15:11:26',
            ),
        ));
        
        
    }
}