<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ValoresUnitariosConstruccionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('valores_unitarios_construccions')->delete();
        
        \DB::table('valores_unitarios_construccions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '788.00',
                'valor_aterior' => '723.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '3339.00',
                'valor_aterior' => '3062.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '788.00',
                'valor_aterior' => '723.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '3339.00',
                'valor_aterior' => '3062.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '5284.00',
                'valor_aterior' => '4846.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '6343.00',
                'valor_aterior' => '5817.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '5284.00',
                'valor_aterior' => '4846.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '6343.00',
                'valor_aterior' => '5817.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2742.00',
                'valor_aterior' => '2514.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2742.00',
                'valor_aterior' => '2514.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3184.00',
                'valor_aterior' => '2920.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}