<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ValoresUnitariosConstruccionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('valores_unitarios_construccions')->delete();

        \DB::table('valores_unitarios_construccions')->insert(array (
            0 =>
            array (
                'id' => 1,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '788.00',
                'valor_aterior' => '723.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            1 =>
            array (
                'id' => 2,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            2 =>
            array (
                'id' => 3,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            3 =>
            array (
                'id' => 4,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            4 =>
            array (
                'id' => 5,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            5 =>
            array (
                'id' => 6,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            6 =>
            array (
                'id' => 7,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            7 =>
            array (
                'id' => 8,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            8 =>
            array (
                'id' => 9,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '3339.00',
                'valor_aterior' => '3062.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            9 =>
            array (
                'id' => 10,
                'tipo' => 1,
                'uso' => 1,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            10 =>
            array (
                'id' => 11,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '788.00',
                'valor_aterior' => '723.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            11 =>
            array (
                'id' => 12,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            12 =>
            array (
                'id' => 13,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            13 =>
            array (
                'id' => 14,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            14 =>
            array (
                'id' => 15,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            15 =>
            array (
                'id' => 16,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            16 =>
            array (
                'id' => 17,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            17 =>
            array (
                'id' => 18,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            18 =>
            array (
                'id' => 19,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '3339.00',
                'valor_aterior' => '3062.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            19 =>
            array (
                'id' => 20,
                'tipo' => 1,
                'uso' => 2,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            20 =>
            array (
                'id' => 21,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            21 =>
            array (
                'id' => 22,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            22 =>
            array (
                'id' => 23,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            23 =>
            array (
                'id' => 24,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            24 =>
            array (
                'id' => 25,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            25 =>
            array (
                'id' => 26,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            26 =>
            array (
                'id' => 27,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            27 =>
            array (
                'id' => 28,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            28 =>
            array (
                'id' => 29,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '5284.00',
                'valor_aterior' => '4846.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            29 =>
            array (
                'id' => 30,
                'tipo' => 2,
                'uso' => 1,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '6343.00',
                'valor_aterior' => '5817.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            30 =>
            array (
                'id' => 31,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1331.00',
                'valor_aterior' => '1220.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            31 =>
            array (
                'id' => 32,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            32 =>
            array (
                'id' => 33,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '1858.00',
                'valor_aterior' => '1703.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            33 =>
            array (
                'id' => 34,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            34 =>
            array (
                'id' => 35,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2639.00',
                'valor_aterior' => '2419.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            35 =>
            array (
                'id' => 36,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            36 =>
            array (
                'id' => 37,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            37 =>
            array (
                'id' => 38,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            38 =>
            array (
                'id' => 39,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '5284.00',
                'valor_aterior' => '4846.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            39 =>
            array (
                'id' => 40,
                'tipo' => 2,
                'uso' => 2,
                'calidad' => 4,
                'estado' => 3,
                'valor' => '6343.00',
                'valor_aterior' => '5817.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            40 =>
            array (
                'id' => 41,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            41 =>
            array (
                'id' => 42,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            42 =>
            array (
                'id' => 43,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            43 =>
            array (
                'id' => 44,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            44 =>
            array (
                'id' => 45,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2742.00',
                'valor_aterior' => '2514.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            45 =>
            array (
                'id' => 46,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            46 =>
            array (
                'id' => 47,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            47 =>
            array (
                'id' => 48,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            48 =>
            array (
                'id' => 49,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            49 =>
            array (
                'id' => 50,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 1,
                'valor' => '1053.00',
                'valor_aterior' => '965.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            50 =>
            array (
                'id' => 51,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 1,
                'valor' => '1588.00',
                'valor_aterior' => '1456.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            51 =>
            array (
                'id' => 52,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 1,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            52 =>
            array (
                'id' => 53,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 2,
                'valor' => '2118.00',
                'valor_aterior' => '1942.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            53 =>
            array (
                'id' => 54,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 2,
                'valor' => '2742.00',
                'valor_aterior' => '2514.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            54 =>
            array (
                'id' => 55,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 2,
                'valor' => '3190.00',
                'valor_aterior' => '2925.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            55 =>
            array (
                'id' => 56,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 1,
                'estado' => 3,
                'valor' => '3184.00',
                'valor_aterior' => '2920.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            56 =>
            array (
                'id' => 57,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 2,
                'estado' => 3,
                'valor' => '3710.00',
                'valor_aterior' => '3402.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
            57 =>
            array (
                'id' => 58,
                'tipo' => 2,
                'uso' => 3,
                'calidad' => 3,
                'estado' => 3,
                'valor' => '4234.00',
                'valor_aterior' => '3882.00',
                'created_at' => now(),
                'updated_at' => now(),
            ),
        ));


    }
}