<?php

namespace App\Http\Constantes;

class Constantes{

    const AREAS = [
        'Roles',
        'Permisos',
        'Usuarios',
        'Trámites',
        'Recepción',
        'Entrega',
        'Entrada',
        'Umas',
        'Auditoría',
        'Categorías de servicios',
        'Servicios',
        'Umas',
        'Subconceptos',
        'Trámites',
        'Trámites',
        'Predios',
        'Valuación',
        'Factor de incremento',
        'Valores unitarios',
        'Oficinas',
        'Avaluos',
        'Consulta',
        'Gestión catasral',
        'Anotaciones y T. A.',
        'Cartografía',
        'Consulta',
        'Efirma',
        'Certificaciones',
        'Certificados'
    ];

    const AREAS_ADSCRIPCION = [
        'Dirección de Catastro',
        'Dirección General del Instituto Registral y Catastral',
        'Delegación Administrativa',
        'Subdirección de Planeación Estratégica',
        'Subdirección Jurídica',
        'Subdirección de Tecnologías de la Información',
        'Departamento de Anotaciones y Trámites Administrativos',
        'Departamento de Operación y Desarrollo de Sistemas',
        'Departamento de Soporte Técnico y Redes',
        'Departamento de Bases de Datos',
        'Departamento de Valuación',
        'Departamento de Gestión Catastral',
        'Departamento de Registro de Cartografía',
        'Departamento de Control Presupuestal y Recursos Financieros',
        'Departamento de Recursos Humanos, Materiales y Servicios Generales',
        'Departamento de Archivo Catastro',
        'Oficina de rentas'
    ];

    const TIPO_PROPIETARIO = [
        'NUDO-PROPIETARIO',
        'USUFRUCTUARIO',
        'JUBILADO O PENSIONADO',
        'FIDUCIARIO',
        'FIDECOMITENTE',
        'PROPIETARIO',
        'POSEEDOR'
    ];

    const TIPO_VIALIDADES = [
        'AMPLIACIÓN',
        'ANDADOR',
        'ARROYO O CANAL',
        'AVENIDA',
        'BOULEVARD',
        'BRECHA',
        'CALLE',
        'CALLEJÓN',
        'CALZADA',
        'CAMINO',
        'CAMINO REAL',
        'CARRETERA',
        'CERRADA',
        'CIRCUITO',
        'CIRCUNVALACIÓN',
        'CONTINUACIÓN',
        'CORREDOR',
        'CUARTEL',
        'DIAGONAL',
        'EJE VIAL',
        'PASAJE',
        'PEATONAL',
        'PERIFÉRICO',
        'PLAZA',
        'PORTAL',
        'PRIVADA',
        'PROLONGACIÓN',
        'RETORNO',
        'SERVIDUMBRE DE PASO',
        'VIADUCTO'
    ];

    const TIPO_ASENTAMIENTO = [
        'AEROPUERTO',
        'AMPLIACIÓN',
        'BARRIO',
        'CANTON',
        'CIUDAD',
        'CIUDAD INSDUSTRIAL',
        'COLONIA',
        'CONDOMINIO',
        'CONJUNTO HABITACIONAL',
        'CORREDOR INDUSTRIAL',
        'COTO',
        'CUARTEL',
        'EJIDO',
        'EX-EJIDO',
        'EXHACIENDA',
        'FRACCIÓN',
        'FRACCIONAMIENTO',
        'GRANJA',
        'HACIENDA',
        'INGENIO',
        'MANZANA',
        'PARAJE',
        'PARQUE INDUSTRIAL',
        'POBLADO',
        'PRIVADA',
        'PROLONGACIÓN',
        'PUEBLO',
        'PUERTO',
        'RANCHERIA',
        'RANCHO',
        'REGIÓN',
        'RESIDENCIAL',
        'RINCONADA',
        'SECCIÓN',
        'SECTOR',
        'SUPERMANZANA',
        'TENENCIA',
        'UNIDAD',
        'UNIDAD HABITACIONAL',
        'VILLA',
        'ZONA FEDERAL',
        'ZONA INDUSTRIAL',
        'ZONA MILITAR',
        'ZONA NAVAL',
    ];

    const VIENTOS = [
        'ANEXO',
        'ESTE',
        'NORESTE',
        'NOROESTE',
        'NORORIENTE',
        'NORPONIENTE',
        'NORTE',
        'OESTE',
        'ORIENTE',
        'PONIENTE',
        'SUR',
        'SURESTE',
        'SUROESTE',
        'SURORIENTE',
        'SURPONIENTE',
    ];

    const CLASIFICACION_ZONA = [
        'NO APLICA',
        'HAB. DEN. SUBURBANA MENOR 50 HAB POR HA',
        'HAB. DEN. BAJA 51 - 150 HAB POR HA',
        'HAB. DEN. MEDIA 151 - 300 HAB POR HA',
        'HAB. DEN. ALTA 301 - 500 HAB POR HA',
        'HAB. DEN. MEDIA SE Y CO,300 HAB POR HA',
        'HAB. DEN. MEDIA CO IN Y SE,300 HABPORHA',
        'SUBCENTRO URBANO HASTA 120 VIV POR HA',
        'CENTRO URBANO HASTA 120 VIV POR HA',
        'CENTRO METROP. HASTA 72 VIV POR HA',
        'ZONA DE MONUMENTOS',
        'ZONA DE TRANSICIÓN',
        'INDUSTRIAL',
        'ÁREAS VERDES YO EQUIPAMIENTO',
        'PARQUE URBANO ECOLÓGICO',
        'EQUIPAMIENTO',
        'INFRAESTRUCTURA',
        'VIALIDAD Y DERECHO DE PASO',
        'PROTECCIÓN ESPECIAL',
        'PROTECCIÓN ECOLÓGICA ESPECIAL',
        'ÁREA NATURAL PROTEGIDA (DECRETADA)',
        'ZONA DE RESTAURACIÓN Y PROT. AMBIENTAL',
        'PROTECCIÓN AGROPECUARIA',
        'PROTECCIÓN USOS AGRICOLAS',
        'PROTECCIÓN USOS PECUARIOS',
        'COMERCIAL Y HABITACIONAL',
    ];

    const CONSTRUCCION_DOMINANTE = [
        'NO APLICA',
        'UN NIVEL (ECONOMICA)',
        'UN NIVEL (IND. LIGERA)',
        'UN NIVEL  (IND. MEDIA)',
        'UN NIVEL  (PESADA)',
        'DOS NIVELES (MEDIA)',
        'DOS NIVELES (MEDIA -SUPERIOR)',
        'DOS  NIVELES  (SUPERIOR)',
        'UNO Y DOS NIVELES  (ECONOMICA - MEDIA)',
        'UNO Y DOS NIVELES  (IND. LIGERA Y MEDIA)',
        'UNO Y DOS NIVELES  (IND. MEDIA - PESADA)',
        'DOS Y TRES NIVELES (MEDIA - SUPERIOR)',
    ];

    const CIMENTACION = [
        'NO APLICA',
        'MAMPOSTERIA',
        'ZAPATA ASILADA',
        'ZAPATAS CORRIDAS',
        'LOSA DE CIMENTACION',
    ];

    const ESTRUCTURAS = [
        'NO APLICA',
        'COLUMNAS CANTERA O MADERA',
        'TRABES, CASTILLOS, CADENA DE CERRAMIENTO',
        'C. CONCRE., TRABES, CAST. Y C. DE CERRAM',
        'C. METALI., TRABES, CAST. Y C. DE CERRAM',
        'MUROS DE CARGA DE CONCRETO ARMADO',
        'MUROS DE CARGA DE CONCRETO ARMADO',
    ];

    const MUROS = [
        'NO APLICA',
        'MULTIPANEL',
        'MADERA Y ADOBE',
        'PIEDRA O ADOBE',
        'TABIQUE Y/O TABICON',
        'TABIQUE Y CONCRETO',
        'COCRETO ARMADO',
    ];

    const ENTREPISOS = [
        'NO APLICA',
        'BOVEDA  CATALANA',
        'MADERA',
        'LOSA RETICULAR',
        'LOSA DE CONCRETO  REFORZADO',
        'ESTRUCTURA METALICA O MIXTA',
        'ARMADURAS DE MONTEN O ANGULOS SENCILLOS',
        'ARMADURAS METALICAS DE PERALTE REGULAR',
        'ARMADURAS  METALICAS DE GRAN PERALTE',
        'TRIDILOSA',
    ];

    CONST TECHOS = [
        'NO APLICA',
        'TEJA',
        'LAMINA DE CARTON',
        'LAMINA ACRILICA',
        'LAMINA GALVANIZADA',
        'LAMINA DE ASBESTO-CEMENTO',
        'LAMINA DE CARTON-ASBESTO-CEMENTO',
    ];

    const PLAFONES = [
        'NO APLICA',
        'MANTA DE CIELO',
        'MEZCLA DE MORTERO',
        'YESO Y/O PASTA',
        'FLASO PLAFON',
        'TABLAROCA',
    ];

    const VIDRIERIA = [
        'NO APLICA',
        'SENCILLOS 3MM, LISO Y/O CHINO',
        'SEMI DOBLE 6MM LISO Y/O CHINO O COLOR',
        'FILTRASOL DE VARIOS ESPESORES',
        'EMPLOMADO',
        'TEMPLADO ',
        'VITRALES',
    ];

    const LAMBRINES = [
        'NO APLICA',
        'MADERAS',
        'AZULEJO',
        'CERAMICA',
    ];

    const PISOS = [
        'NO APLICA',
        'CEMENTO',
        'MADERA',
        'MOSAICO',
        'CERAMICA',
        'LOSETA DE BARRO',
        'PARQUET',
        'DUELA',
    ];

    const HERRERIA = [
        'NO APLICA',
        'FIERRO FORJADO',
        'ESTRUCTURAL',
        'TUBULAR',
        'ALUMINIO DE VARIOS CALIBRES',
    ];

    const PINTURA = [
        'NO APLICA',
        'A LA CAL',
        'VINILICA',
        'ESMALTE',
    ];

    const CARPINTERIA = [
        'NO APLICA',
        'MADERA ECONOMICA',
        'MADERA DE MEDIANA CALIDAD',
        'MADERAS FINAS',
    ];

    const APLANADOS = [
        'NO APLICA',
        'ESTUCO',
        'BARRO',
        'MEZCLA DE MORTERO',
        'YESO ',
        'PASTAS',
    ];

    const RECUBRIMIENTO_ESPECIAL = [
        'NO APLICA',
        'PAPEL TAPIZ',
        'ALFOMBRA',
        'MADERA',
        'PIEDRA ',
        'AZULEJO',
    ];

    const HIDRAULICA = [
        'NO APLICA',
        'GALVANIZADA',
        'GALVANIZADA, COBRE',
        'COBRE Y/O PVC',
    ];

    const SANITARIA = [
        'NO APLICA',
        'ALBAÑAL DE CEMENTO',
        'ALBAÑAL FORJADO',
        'PVC VARIOS DIAMETROS',
    ];

    const ELECTRICA = [
        'NO APLICA',
        'VISIBLES',
        'OCULTA',
    ];

    const GAS = [
        'NO APLICA',
        'GALVANIZADA',
        'COBRE',
    ];

    const ESPECIALES = [
        'NO APLICA',
        'GAS ESTACIONARIO',
        'INTERFON',
        'CIRCUITO CERRADO DE TV',
    ];

    const USO_PREDIO = [
        'AEROPUERTO',
        'AGENCIA DE AUTOS',
        'AGENCIA DE VIAJES',
        'AGOSTADERO',
        'AGRICOLA',
        'AGROPECUARIO',
        'ALBERCA',
        'ALBERGUE',
        'APARTAMENTO',
        'ASILO',
        'ASISTENCIA PUBLICA',
        'AUTO LAVADO',
        'BALDIO',
        'BALNEARIO',
        'BANCOS',
        'BAÑOS',
        'BASCULA',
        'BIBLIOTECA',
        'BILLARES',
        'BODEGA',
        'CABAÑA',
        'CAMPO DE GOLF',
        'CANTINA CABARET',
        'CARCEL',
        'CARNICERIA',
        'CASA HABITACION',
        'CASA HOGAR',
        'CASETA DE POLICIA',
        'CASETA DE VIGILANCIA',
        'CENTRAL ELECTRICA',
        'CLINICA',
        'CLUB',
        'COCHERA',
        'COMERCIO',
        'COMITE EJIDAL',
        'CONSULTORIO MEDICO',
        'CONVENTO',
        'CUARTEL DE BOMBEROS',
        'DEPOSITO DE AGUA',
        'DIREC DE TRANSITO',
        'DISPENSARIO',
        'EMPACADORA',
        'EN CONSTRUCCION',
        'ERIAZO',
        'ESCUELA PARTICULAR',
        'ESCUELA PUBLICA',
        'ESTABLO',
        'ESTACION FFCC',
        'ESTADIO',
        'FABRICAS',
        'FARMACIA',
        'FRUTERIA',
        'GALERA',
        'GASERA',
        'GASOLINERA',
        'GRANJA',
        'GUARDERIA',
        'HOSPITAL',
        'HOTEL',
        'HUERTA',
        'HUMEDAD',
        'IGLESIAS',
        'INFRAESTRUCTURA',
        'INSTALACIONES DEPORTIVAS',
        'JARDIN',
        'KIOSCO',
        'LABORATORIO',
        'LADRILLERA',
        'LAVANDERIA PUBLICA',
        'LICORERIA VINATERIA',
        'LIENZO CHARRO',
        'MADERERIA',
        'MERCADO',
        'MOLINO',
        'MONTE ALTO',
        'MONTE BAJO',
        'MONUMENTO HISTORICO',
        'NAVE INDUSTRIAL',
        'NO CLASIFICA',
        'OFICINA DE VENTAS',
        'OFICINAS',
        'OFICINAS DE GOBIERNO',
        'OFICINAS GENERALES',
        'PANTEON',
        'PELUQUERIA',
        'PENSION AUTOMOVILES',
        'PENTH HOUSE',
        'PLANTA INDUSTRIAL',
        'PLANTA TRATADORA DE AGUA',
        'PLAZA CIVICA',
        'PLAZA DE TOROS',
        'POZO PROFUNDO',
        'PRESIDENCIA MPAL',
        'PROPIEDAD FEDERAL',
        'RADIODIFUSORA',
        'RASTRO',
        'RESTAURANTE',
        'RIEGO MECANICO',
        'RIEGO POR GRAVEDAD',
        'RUINAS',
        'SALA DE BELLEZA',
        'SALA DE ESPECTACULOS',
        'SALON DE FIESTAS',
        'SASTRERIA',
        'SERVIDUMBRE DE PASO',
        'SILVOPASTORIL',
        'SIN USO DE PREDIO',
        'SINDICATO',
        'SUPERMERCADO',
        'TALLER',
        'TANQUE METALICO',
        'TEMPORAL DE PRIMERA',
        'TEMPORAL DE SEGUNDA',
        'TEMPORAL DE TERCERA',
        'TENERIA',
        'TERMINAL DE CAMIONES',
        'TINTORERIA',
        'UNIDAD DEPORTIVA',
        'UNIDAD HOGAR',
        'USO COMERCIAL',
        'VECINDAD',
        'VETERINARIA',
        'VIVERO',
        'ZAHURDA',
        'ZAPATERIA',
        'ZOOLOGICO',
    ];

    const UBICACION_PREDIO = [
        'INTERMEDIO',
        'ESQUINA',
        'TRANSVERSAL CON FRENTES NO CONTIGUOS',
        'CABECERA',
        'MANZANERO',
        'INTERIOR',
    ];

    const AÑOS = [
        '2024' => '2024',
        '2023' => '2023',
    ];

    const SOLICITANTES = [
        'Escrituración social',
        'Notaría',
        'Oficialia de partes',
        'Usuario'
    ];

    const ACCIONES_PADRON = [
        'ACLARACION DE DESGLOSE CATASTRAL',
        'ACLARACIÓN ESCRITURA COMP-VENTA INMUEBLE',
        'ACLARACIONES',
        'ACT. COP. PROG COPROPIETARIOS',
        'ACTUALIZACION GRAL.',
        'ACTUALIZACION POR ENVIO DE RENTAS',
        'ACTUALMENTE',
        'ACUERDO EJECUTIVO DEL ESTADO',
        'ACUERDO RESOLUTORIO',
        'ACUSES DE RECIBO',
        'ADJ. DISOLUCION Y LIQUIDACION FONDO SOC.',
        'ADJUDICACION DE BIEN INMUEBLE',
        'ADJUDICACION DE INMUEBLE (JUICIO)',
        'ADJUDICACION EXTINCION PARCIAL DE PROP',
        'ADJUDICACIÓN JUDICIAL EN REBELDÍA',
        'ADJUDICACION PARCIAL POR SUCESION',
        'ADJUDICACIÓN POR EXTINCIÓN PARCIAL DE COPROPIEDAD',
        'ADJUDICACION POR HERENCIA',
        'ADJUDICACION POR HERENCIA Y DONACION',
        'ADJUDICACIÓN POR REMATE',
        'ADJUDICACION POR SUCESION TESTAMENTARIA',
        'ADJUDICACION SUCESION INTESTAMENTARIA',
        'AFECTACIÓN POR APERTURA DE CALLE',
        'ALTA EN EL PADRON',
        'ALTA PARA BASE DEL IMPUESTO PREDIAL',
        'ALTA POR AUTORIZACIÓN DE SUBDIVISIÓN',
        'ALTA POR CAMBIO DE OFICINA',
        'ALTA POR CAMBIO DE REGIMEN',
        'ALTA POR CORETT',
        'ALTA POR DESGLOSE',
        'ALTA POR INSUS',
        'ALTA POR OMISIÓN EN CAPTACIÓN',
        'ALTA POR PREDIO IGNORADO',
        'ALTA POR REESTRUCTURACION DE CUENTA',
        'ALTA POR S.U.M.A.',
        'ALTA REGISTRO AGRARIO NACIONAL',
        'APLICACIÓN DE BIENES HEREDITARIOS',
        'APORTACION AL CAPITAL SOCIAL',
        'APORTACIÓN EN ESPECIE DE INMUEBLE',
        'ASESORIAS',
        'AUMENTO AL VALOR',
        'AVALÚO EXTERNO',
        'AVALUO PARA BASE DEL IMPUESTO PREDIAL',
        'AVALUO POR MODERNIZACION CATASTRAL',
        'AVALUO TECNICO',
        'AVISO ACLARATORIO DE CORRECCION',
        'AVISO AL FISCO',
        'AVISO PREVENTIVO',
        'BAJA',
        'BAJA PARCIAL DE CAUDAL HEREDITARIO',
        'BAJA PARCIAL POR DILIGENCIAS DE INF.',
        'BAJA PARCIAL POR DIVICION Y PARTICION',
        'BAJA PARCIAL POR DONACION',
        'BAJA PARCIAL POR INSUS',
        'BAJA PARCIAL POR JUICIO ORDINARIO CIVIL',
        'BAJA PARCIAL POR JUICIO SUCESORIO',
        'BAJA PARCIAL POR PRESCRIPCIÓN',
        'BAJA PARCIAL POR VARIACION CATASTRAL',
        'BAJA POR AFECTACIÓN',
        'BAJA POR AUTORIZACIÓN DE SUBDIVISIÓN',
        'BAJA POR CAMBIO DE LOCALIDAD',
        'BAJA POR CAMBIO DE REGIMEN',
        'BAJA POR CANCELACIÓN DE SUBDIVISION',
        'BAJA POR CONCILIACION DE INFORM.',
        'BAJA POR DESGLOSE',
        'BAJA POR FUERA DEL LINDERO MUNICIPAL',
        'BAJA POR FUSION',
        'BAJA POR ORDEN JUDICIAL',
        'BAJA POR VARIACION CATASTRAL',
        'CAMBIO DE CUENTA PREDIAL',
        'CAMBIO DE LOCALIDAD',
        'CAMBIO DE REGIMEN',
        'CAMBIO DE SISTEMA',
        'CANCELACIÓN DE ASEGURAMIENTO',
        'CANCELACION DE AVISO ANTERIOR',
        'CANCELACION DE ESCRITURA O TRASLADO',
        'CANCELACIÓN DE FUSION',
        'CANCELACIÓN DE RESERVA DE DOMINIO',
        'CANCELACIÓN DE SUBDIVISIÓN',
        'CANCELACIÓN DE TÍTULO DE PROPIEDAD',
        'CANCELACION POR DUPLICIDAD',
        'CERTIFICACION DE DOCUMENTOS',
        'CERTIFICADO NEGATIVO',
        'CERTIFICADO REGISTRO',
        'CERTIFICADOS DE HIST',
        'CESION DE DERECHOS',
        'CESION DE DERECHOS HEREDITARIOS',
        'CESION ONEROSA DERECHOS HEREDITARIOS',
        'COMPRA PARCIAL',
        'COMPRA VENTA',
        'COMPRA VENTA ADCORPUS RESERVA DE DOMINIO',
        'COMPRA VENTA DE USUFRUTO VITALICIO',
        'COMPRA VENTA TOTAL',
        'COMPRA VENTA TOTAL CON RESERVA DOMINIO',
        'COMPRAVENTA A PLAZOS',
        'COMPRAVENTA AD-CORPUS',
        'COMPRA-VENTA DE ACCIONES Y DERECHOS',
        'COMPRA-VENTA DE LA NUDA PROPIEDAD',
        'COMPRA-VENTA DERECHOS DE COOPROPIEDAD',
        'COMPRA-VENTA INMUEBLE MUTUO Y GARANTIA HIPOTECARIA',
        'CON. TRANSMICIÓN PROP. EJEC. DERECHO EX',
        'CONCILIADO',
        'CONDONACIONES',
        'CONSOLIDACIÓN DE PROPIEDAD',
        'CONSOLIDACION DE SOCIEDADES',
        'CONSOLIDACION DE USUFRUCTO',
        'CONST. DE SERVIDUMBRES LEGALES DE PASO',
        'CONST. DISOLUCION DE COOPROPIEDAD INM.',
        'CONST. GRATUITA DEL USUFRUCTO VITALICIO',
        'CONSTANCIA DE NUMERO OFICIAL',
        'CONSTITUCION DE REGIMEN EN CONDOMINIO',
        'CONTRATO DE ASOCIACIÓN EN PARTICIPACIÓN',
        'CONTRATO DE COMPRA-VENTA DE DER. DE COP.',
        'CONTRATO DE DESINCORPORACIÓN DE INMUEBLE',
        'CONTRATO DE DONACIÓN',
        'CONTRATO DE PAGO',
        'CONTRATO DE PERMUTA DE INMUEBLE',
        'CONTRATO DE RENTA VITALICIA',
        'CONVENIO DE APORTACION DE INMUEBLE',
        'CONVENIO DE REVOCACIÓN DE INST. PUB.',
        'COPIAS DE DIFERENTES RECEPTORIAS',
        'COPIAS DE DOCTOS.',
        'COPIAS DE PLANOS',
        'CUMPLIMIENTO DE CONVENIO JUDICIAL',
        'DACION EN COMPENSACION',
        'DACION EN PAGO',
        'DENUNCIA DEL USUFRUCTO VITALICIO',
        'DENUNCIAS',
        'DERECHOS FIDUCIARIOS',
        'DESGLOSE CATASTRAL',
        'DESISTIMIENTO DE ACCIÓN PENAL',
        'DETERM. UBIC. FISICA',
        'DILIGENCIAS DE JURISDICCIÓN VOLUNTARIA',
        'DILIGENCIAS INF TESTIMONIAL AD PERPETUAM',
        'DISOLUCION DE COOPROPIEDAD DE INMUEBLE',
        'DISOLUCION DE COPROPIEDAD',
        'DIVISION DE COSA COMUN',
        'DIVISIÓN POR RESOLUCIÓN JUDICIAL',
        'DIVISIÓN Y PARTICIÓN DE COSA COMÚN',
        'DIVISION Y PARTICION PARCIAL DE C COMÚN',
        'DONACION A TITULO GRATUITO',
        'DONACIÓN CON RESERVA DE USUFRUCTO VITALICIO',
        'DONACION DE ACCIONES Y DERECHOS',
        'DONACIÓN DE DERECHOS DE COPROPIEDAD',
        'DONACION DE INMUEBLE',
        'DONACION DE INMUEBLE REMUNERATORIA',
        'DONACION DE LA NUDA PROPIEDAD',
        'DONACION DE USUFRUCTO',
        'DONACIÓN ONEROSA',
        'DONACIÓN PURA Y SIMPLE',
        'DOTACIÓN DE TERRENOS',
        'EJ. DE SCIA. Y EXCLUS. DE BIENES HEREDI.',
        'EJECUCIÓN PARCIAL DE FIDEICOMISO',
        'ELAB. AVALUO P/ ISAI',
        'ENAGENACION A TITULO GRATUITO',
        'ENAJENACIÓN DE INMUEBLE',
        'ESCISION DE LA SOCIEDAD',
        'EXEDENCIA DE SUPERFICIE',
        'EXPROPIACION POR CAUSA DE UTILIDAD PUB',
        'EXTINCION DE FIDEICOMISO',
        'EXTINCIÓN DE USUFRUCTO VITALICIO',
        'EXTINCIÓN DEL REGIMEN DE PROP. EN COND.',
        'EXTINCIÓN PARCIAL DE FIDEICOMISO',
        'FIDEICOMISO',
        'FORMALIZACION C. COMPRAVENTA EN REBELDIA',
        'FORMALIZACION DEL CONTRATO COMPRAVENTA',
        'FRACCIONAMIENTOS',
        'FUSION DE PREDIO',
        'FUSION DE SOCIEDADES',
        'FUSIONES',
        'I S A I',
        'IMPUESTO PRED RUSTICO',
        'IMPUESTO PRED.EJIDAL',
        'IMPUESTO PRED.URBANO',
        'INC. APORTACION AL PATRIMONIO FIDEICO',
        'INCIDENTE NO ESPECIFICADO',
        'INDEX. VALORES INPC',
        'INDEXACION POR INPC',
        'INFORM. PROP. O POS.',
        'INFORMACION AD PERPETUAM',
        'INFRACCIONES Y SANC.',
        'INICIO DE HISTORIA (TARJETA)',
        'INICIO DE HISTORIA (TOMO Y FOJAS)',
        'INM MOSTRENCOS LOCAL',
        'INMUEB MOSTRENCOS ',
        'INMUEBLE EN EJECUCIÓN DE FIDEICOMISO',
        'INSPECCION OCULAR',
        'INSTITUTO NACIONAL DEL SUELO SUSTENTABLE',
        'JUICIO AMPARO',
        'JUICIO MERCANTIL EJECUTIVO',
        'JUICIO ORDINARIO CIVIL',
        'JUICIO SUCESORIO INTESTAMENTARIO',
        'JUICIO SUCESORIO TESTAMENTARIO',
        'JUICIO SUMARIO CIVIL',
        'JUICIO SUMARIO CIVIL HIPOTECARIO',
        'LA CUENTA A OTRO TOMO Y FOLIO',
        'LICENCIA CONSTRUCCION',
        'LIQUIDACIÓN DE SOCIEDAD CONYUGAL',
        'LIQUIDACION, PARTICION Y ADJ. DE CAUDAL',
        'LOTIFICACIÓN',
        'MATERIAL PARA OFICINAS FOR.',
        'MED Y DESL CURV NIV.',
        'MEDICIONES Y DESLINDES',
        'MOD VALOR CATASTRAL',
        'MODIF DATOS ADMINIST',
        'MODIF.A CONSTRUCCION',
        'MODIFICACION POR AVALUO',
        'MODIFICACION POR DESGLOSE',
        'MODIFICACIÓN POR PRESCRIPCIÓN POSITIVA',
        'MOV. PARCIAL POR DILIGENCIA DE INFORMACI',
        'MOV. POR PROG. USU.',
        'MOVIMIENTO POR JUEZ MENOR MUNICIPAL',
        'MOVIMIENTOS DE PERSONAL',
        'NOMENCLATURA',
        'NOTA',
        'NOTIFICACION DE AVALUO TECNICO',
        'NULIDAD ABS DILIGENCIAS JURISDICCION ABS',
        'NULIDAD ABSOLUTA DE LA ESCRITURA',
        'NULIDAD ABSOLUTA SUCESORIO INTESTAMENTAR',
        'NULIDAD DE DILIGENCIAS AD. PERPETUAM',
        'NULIDAD DE EXPROPIACIÓN',
        'NULIDAD DE JUICIO CONCLUIDO',
        'NULIDAD DE RECT. DE SUPERFICIE',
        'OFICIOS',
        'OTORGAMIENTO DE TITULO DE PROPIEDAD',
        'PADRONES',
        'PERITOS VALUADOR',
        'PERMUTA',
        'PERMUTA ACCIONES Y DERECHOS DE INMUEBLE',
        'PERMUTA CON DONACIÓN',
        'POR GANANCIAS CONYUGALES',
        'PRE-AVALUO TECNICO',
        'PREDIO EJID. FORANEO',
        'PREDIO EJIDAL LOCAL',
        'PREDIOS IGNORADOS',
        'PRESCRIPCION',
        'PRESCRIPCIÓN POSITIVA Y ADQUISITIVA',
        'PRIMER ANTECEDENTE',
        'PROCEDE',
        'PROGRAMA DE CERTIFICACION DE PROCEDE',
        'PROTOCOLIZACIÓN',
        'PROTOCOLIZACION DE CONTRATO DE USUFRUCTO',
        'PROTOCOLIZACIÓN DE CONTRATO PRIVADO DE DONACIÓN',
        'PROTOCOLIZACIÓN JUICIO SUCESORIO INTESTAMENTARIO',
        'PROTOCOLIZACIÓN JUICIO SUCESORIO TESTAMENTARIO',
        'PUBLICACIONES OFICIALES',
        'RECISIÓN DE COMPRA-VENTA',
        'RECTIFICACION DE MEDIDAS',
        'RECTIFICACIÓN DE NOMBRE',
        'RECTIFICACION DE NOTARIO',
        'RECURSO DE APELACION',
        'RECURSO DE REVOCACION',
        'REESTRUC. DE CUENTA',
        'REGISTRO EN OTRO TOMO Y FOLIO',
        'REGISTRO VALOR UNIT.',
        'REINSCRIPCION',
        'RELOTIFICACIÓN',
        'REMATE FISCAL',
        'REMATE JUDICIAL',
        'REMUNERACION DE PROPIEDAD',
        'RENUNCIA DE USUFRUCTO',
        'REPRESENTACIÓN NOTARIAL',
        'RESCISIÓN DE CONTRATO DE DONACIÓN',
        'RESOLUCIÓN DEFINITIVA',
        'RESTITUCION DE LA PROPIEDAD',
        'REVERSIÓN DE FIDEICOMISO',
        'REVERSION PARCIAL EN EJECUCION DE FIDEIC',
        'REVISIÓN INMUEBLE EJECUCIÓN FIDEICOMISO',
        'SAN. Y SUSP.A PERITO',
        'SUBDIVISION DE PREDIO',
        'SUB-DIVISIONES RUST.',
        'SUB-DIVISIONES URBANAS',
        'SUBROGACIÓN DE DERECHOS LITIGIOSOS',
        'SUCESION DE DERECHOS',
        'SUCESIÓN EXTRAJUDICIAL INTESTAMENTARIA',
        'SUCESIÓN EXTRAJUDICIAL TESTAMENTARIA',
        'SUPERVISION D AVALUO',
        'SURGE EL PREDIO',
        'SURGEN LOS PREDIOS',
        'SUSCRIPCIÓN Y PAGO PARCIAL DE ACCIONES',
        'SUSPENCION POR ORDEN JUDICIAL',
        'TRAMITACIÓN EXTRAJUDICIAL',
        'TRAMITES A LA DIRECCION',
        'TRANSMICION DE ACCIONES Y DERECHOS',
        'TRANSMISIÓN',
        'TRANSMISION DE INMUEBLE',
        'TRANSMISION DE NUDA PROP. Y/O  USUFRUCTO',
        'VALIDACION Y ACT.',
        'VALUACION',
        'VARIACION CATASTRAL',
        'VENTA DE ACCIONES Y DERECHOS',
        'VENTA PARCIAL',
        'VENTA TOTAL',
        'VENTANILLA UNICA',
        'VERIFICACION',
        'XXXXXX',
    ];

    const DOCUMENTO_ENTRADA = [
        'ESCRITURACIÓN SOCIAL',
        'ESCRITURA PÚBLICA',
        'ESCRITURA PRIVADA',
        'TÍTULO DE PROPIEDAD PARCELARIO',
        'TÍTULO DE PROPIEDAD SOLAR URBANO',
        'CONTRATO DE COMPRAVENTA',
    ];

    const ESTADOS = [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de México',
        'Coahuila',
        'Colima',
        'Durango',
        'Estado de México',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
    ];

    const ESTADO_CIVIL = [
        'CASADO',
        'SOLTERO',
        'VIUDO',
        'DIVORCIADO'
    ];

    const CERTIFICACIONES = [
        'CERTIFICADO DE REGISTRO CATASTRAL',
        'CERTIFICADO DE REGISTRO CATASTRAL ELECTRÓNICO',
        'CERTIFICADO DE HISTORIA CATASTRAL',
        'CERTIFICADO NEGATIVO CATASTRAL',
        'NOTIFICACIÓN DE VALOR CATASTRAL',
        'CEDULA DE ACTUALIZACIÓN'
    ];

    const RECHAZOS_AVISOS = [
        'CAPÍTULO CUARTO Artículo 94' => 'Los documentos que deben acompañarse al aviso de adquisiciones de inmuebles a que se refiere el artículo 85 de la Ley son: el Certificado de Registro Catastral, la Constancia de no adeudo de Contribuciones Municipales y el Avalúo del inmueble practicado por un Perito Valuador autorizado por el Instituto.',
        'CAPÍTULO CUARTO Artículo 95 I.' => 'Acompañen los anexos que se identifican en el artículo que antecede con vigencia no mayor a 3 meses.',
        'CAPÍTULO CUARTO Artículo 95 II.' => 'Coincida el número de predio que señala el aviso con el del certificado catastral adjunto, siendo que solamente se podrá referir a un bien inmueble por aviso presentado.',
        'CAPÍTULO CUARTO Artículo 95 III.' => 'Indique en el apartado de la naturaleza del acto o concepto de operación, el tipo de acto que se está realizando, siendo que sólo podrá referirse a un tipo de operación por lo cual no podrá presentarse más de una operación por traslado presentado.',
        'CAPÍTULO CUARTO Artículo 95 IV.' => 'Consigne el número de la escritura, distinguiendo si se trata de escritura pública o privada.',
        'CAPÍTULO CUARTO Artículo 95 V.' => 'Indique la fecha de firma de la escritura, esto a fin de determinar si el aviso se está presentando en tiempo conforme a la Ley.',
        'CAPÍTULO CUARTO Artículo 95 VI.' => 'Coincida el nombre del transmitente señalado en el aviso con el asentado en el certificado catastral.',
        'CAPÍTULO CUARTO Artículo 95 VII.' => 'Se especifique si el predio motivo de transmisión es terreno rústico o urbano.',
        'CAPÍTULO CUARTO Artículo 95 VIII.' => 'Coincida la ubicación del predio señalada en el aviso, con la asentada en el certificado catastral, en la constancia de no adeudo de contribuciones municipales y en el avalúo, es decir, que se refiera al mismo predio, considerando la calle, número oficial, lote, manzana, indicando asimismo sus medidas y colindancias; en los casos en que dichos datos se actualicen o cambien, se deberá indicar tal situación.',
        'CAPÍTULO CUARTO Artículo 95 IX.' => 'Coincida la superficie de terreno señalado en el aviso, con la consignada en el certificado catastral y en el avalúo. Para efectos de lo anterior, se entiende por superficie notarial, aquella que de manera expresa se indica en el aviso de adquisición de inmuebles, no así aquella que se deduzca o determine con base a las medidas del predio.',
        'CAPÍTULO CUARTO Artículo 95 X.' => 'El aviso se encuentre firmado y sellado por el notario público que dio fe del acto traslativo de dominio.',
        'CAPÍTULO CUARTO Artículo 95 XI.' => 'El avalúo catastral que se presente corresponda al predio objeto de la transmisión, verificando la superficie, la ubicación, número de predio, clave catastral y uso, y que haya sido practicado por Perito Valuador autorizado por el Instituto.',
        'CAPÍTULO CUARTO Artículo 95 XII.' => 'La constancia de no adeudo de contribuciones Municipales, corresponda al predio motivo de la transmisión.',
        'CAPÍTULO CUARTO Artículo 95 XIII.' => 'Copia del pago del Impuesto sobre adquisición de bienes inmuebles realizado ante la autoridad municipal correspondiente.',
        'CAPÍTULO CUARTO Artículo 95 XIV.' => 'Pago de los derechos fiscales para efecto de la revisión del aviso traslativo de dominio correspondiente al predio que se revisa, en términos de la Ley de Hacienda del Estado de Michoacán y la Ley de Ingresos del Estado para el ejercicio fiscal que corresponda.',
        'CAPÍTULO CUARTO Artículo 95 XV.' => 'Como medida de seguridad jurídica, el aviso no deberá tener borraduras, enmendaduras ni alteraciones evidentes al momento de su revisión.',
        'CAPÍTULO CUARTO Artículo 96.' => 'Si de la revisión de un aviso de adquisición de inmuebles se detectan diferencias o anomalías, deberá devolverse el aviso de manera inmediata precisando los motivos de la devolución, para su corrección o aclaración correspondiente.',
    ];

}
